#%RAML 1.0 NamedExample
exampleJson:

  {
    "accountNumber" : 123456789,
    "address" : [
      {
        "typeOfAddress" : "home",
        "city" : "hyderabad",
        "zip" : 0123
      },
      {
        "typeOfAddress" : "work",
        "city" : "New York",
        "zip" : 9999
      }
    ]
  }